spring.application.name=transport-events

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/transportevents
spring.datasource.username=postgres
spring.datasource.password=Dballz05post!

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect